CREATE USER __READERUSERNAME__ WITH PASSWORD '__READERPASSWORD__';
GRANT USAGE ON SCHEMA __SCHEMA_NAME__ TO __READERUSERNAME__;
GRANT SELECT ON ALL TABLES IN SCHEMA __SCHEMA_NAME__ TO __READERUSERNAME__;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA __SCHEMA_NAME__ TO __READERUSERNAME__;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA __SCHEMA_NAME__ TO __READERUSERNAME__;

CREATE USER __SUPERUSERNAME__ WITH PASSWORD '__SUPERPASSWORD__';
GRANT USAGE ON SCHEMA __SCHEMA_NAME__ TO __SUPERUSERNAME__;
GRANT ALL ON ALL TABLES IN SCHEMA __SCHEMA_NAME__ TO __SUPERUSERNAME__;
GRANT ALL ON ALL SEQUENCES IN SCHEMA __SCHEMA_NAME__ TO __SUPERUSERNAME__;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA __SCHEMA_NAME__ TO __SUPERUSERNAME__;