version: '3.7'

services:
  sftp:
    image: atmoz/sftp:latest
    container_name: sshftp
    restart: always
    expose:
      - "22"
    ports:
      - "2222:22"
    command:
      - ${SFTP_USERNAME}:${SFTP_PASSWORD}:1001::${DATA_STORE}   # syntax: user:password[:e][:uid[:gid[:dir1[,dir2]...]]]
    volumes:
      - ./${DATA_STORE}:/home/${SFTP_USERNAME}/${DATA_STORE}
      - ./keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key 
      - ./keys/ssh_host_ed25519_key.pub:/home/${SFTP_USERNAME}/.ssh/ssh_host_ed25519_key.pub:ro
      - ./keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key \
      - ./keys/ssh_host_rsa_key.pub:/home/${SFTP_USERNAME}/.ssh/ssh_host_rsa_key.pub:ro

networks:
  sshftp-net:
    name: sshftp-net
    driver: bridge